<?php
/**
 * Laptop data check - table existence, row counts, legacy export.
 * Run: php run-laptop-check.php
 */
$errFile = __DIR__ . '/docs/reports/laptop-check-err.txt';
@mkdir(dirname($errFile), 0755, true);
try {
    require_once __DIR__ . '/config.php';
} catch (Throwable $e) {
    file_put_contents($errFile, "config: " . $e->getMessage());
    exit(1);
}

$tables = ['stores','daily_kpis','vendors','products','inventory','orders','employees','employee_locations','time_shifts','time_punch_events'];
$reportDir = __DIR__ . '/docs/reports';
$exportDir = __DIR__ . '/artifacts/legacy-export';
$exportSql = $exportDir . '/legacy-pos-tables.sql';

foreach ([$reportDir, $exportDir] as $d) {
    if (!is_dir($d)) mkdir($d, 0755, true);
}

$host = DB_HOST;
$db = DB_NAME;
$user = DB_USER;
$pass = DB_PASS;

$results = [];
$pdo = getDB();
foreach ($tables as $t) {
    $exists = $pdo->query("SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=" . $pdo->quote($t) . ")")->fetchColumn();
    $count = 0;
    if ($exists === 't' || $exists === true || $exists === 1) {
        $count = (int) $pdo->query("SELECT COUNT(*) FROM \"$t\"")->fetchColumn();
    }
    $results[$t] = ['exists' => (bool) $exists, 'rows' => $count];
}

$utc = gmdate('Y-m-d\TH:i:s\Z');
$existingTables = array_filter($tables, fn($t) => $results[$t]['exists']);
$missingTables = array_filter($tables, fn($t) => !$results[$t]['exists']);

// pg_dump only if legacy-pos-tables.sql missing
$dumpCreated = false;
if (!file_exists($exportSql) && !empty($existingTables)) {
    $tFlags = implode(' ', array_map(fn($t) => "-t $t", $existingTables));
    $cmd = sprintf('pg_dump -h %s -U %s -d %s --no-owner --no-privileges %s 2>/dev/null', escapeshellarg($host), escapeshellarg($user), escapeshellarg($db), $tFlags);
    putenv("PGPASSWORD=$pass");
    $out = shell_exec($cmd);
    if ($out !== null) {
        file_put_contents($exportSql, $out);
        $dumpCreated = true;
    }
}

// docs/reports/laptop-data-check.md
$md = "# Laptop Data Check Report\n\n";
$md .= "## DB Connection\n";
$md .= "- **Source:** config.php (no .env found)\n";
$md .= "- **Host:** $host\n";
$md .= "- **Database:** $db\n";
$md .= "- **User:** $user\n\n";
$md .= "## Table Existence & Row Counts\n";
$md .= "| Table | Exists | Rows |\n|-------|--------|------|\n";
foreach ($tables as $t) {
    $ex = $results[$t]['exists'] ? '1' : '0';
    $md .= "| $t | $ex | {$results[$t]['rows']} |\n";
}
$md .= "\n## Missing Tables\n";
foreach ($missingTables as $t) {
    $md .= "- **$t** (missing)\n";
}
$md .= "\n## Schema & Seed Scripts\n";
$md .= "| Script | Exists | Covers |\n|--------|--------|--------|\n";
$md .= "| database/schema-postgresql.sql | " . (file_exists(__DIR__.'/database/schema-postgresql.sql') ? 'yes' : 'no') . " | stores, daily_kpis |\n";
$md .= "| database/inventory-schema-postgresql.sql | " . (file_exists(__DIR__.'/database/inventory-schema-postgresql.sql') ? 'yes' : 'no') . " | vendors, products, inventory, orders |\n";
$md .= "| database/migrate-timeclock.sql | " . (file_exists(__DIR__.'/database/migrate-timeclock.sql') ? 'yes' : 'no') . " | employees, employee_locations, time_shifts, time_punch_events |\n";
$md .= "| seed-inventory.php | " . (file_exists(__DIR__.'/seed-inventory.php') ? 'yes' : 'no') . " | vendors, products, inventory (sample data) |\n";
$md .= "| seed-timeclock.php | " . (file_exists(__DIR__.'/seed-timeclock.php') ? 'yes' : 'no') . " | employees, employee_locations, time_shifts (sample data) |\n";
$md .= "\n## Export\n";
$md .= "- **File:** artifacts/legacy-export/legacy-pos-tables.sql\n";
$md .= "- **Export UTC:** $utc\n";
$md .= "- **Created:** " . ($dumpCreated ? 'yes' : (file_exists($exportSql) ? 'already existed' : 'no (no tables)')) . "\n";
file_put_contents($reportDir . '/laptop-data-check.md', $md);

// artifacts/legacy-export/README.md
$readme = "# Legacy POS Tables Export\n\n";
$readme .= "- **Database:** $db\n";
$readme .= "- **Export UTC:** $utc\n";
$readme .= "- **Row counts:**\n\n";
$readme .= "| Table | Rows |\n|-------|------|\n";
foreach ($existingTables as $t) {
    $readme .= "| $t | {$results[$t]['rows']} |\n";
}
$readme .= "\nGenerated by run-laptop-check.php\n";
file_put_contents($exportDir . '/README.md', $readme);

$statusFile = __DIR__ . '/docs/reports/laptop-check-status.json';
file_put_contents($statusFile, json_encode([
    'report' => $reportDir . '/laptop-data-check.md',
    'export' => $exportSql,
    'readme' => $exportDir . '/README.md',
    'dump_created' => $dumpCreated,
    'row_counts' => array_map(fn($r) => $r['rows'], $results),
], JSON_PRETTY_PRINT));

echo "Report: docs/reports/laptop-data-check.md\n";
echo "Export: $exportSql\n";
echo "README: artifacts/legacy-export/README.md\n";
