<?php
/**
 * Standalone laptop check - no config.php (avoids die on connection fail).
 * Run: php run-laptop-check-standalone.php
 */
$host = 'localhost';
$db = 'artisan_den';
$user = 'artisan_user';
$pass = 'artisan_pass_123';

$tables = ['stores','daily_kpis','vendors','products','inventory','orders','employees','employee_locations','time_shifts','time_punch_events'];
$reportDir = __DIR__ . '/docs/reports';
$exportDir = __DIR__ . '/artifacts/legacy-export';
$exportSql = $exportDir . '/legacy-pos-tables.sql';

foreach ([$reportDir, $exportDir] as $d) {
    if (!is_dir($d)) mkdir($d, 0755, true);
}

$results = [];
try {
    $pdo = new PDO("pgsql:host=$host;dbname=$db", $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
    foreach ($tables as $t) {
        $exists = $pdo->query("SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=" . $pdo->quote($t) . ")")->fetchColumn();
        $count = 0;
        if ($exists === 't' || $exists === true || $exists === 1) {
            $count = (int) $pdo->query("SELECT COUNT(*) FROM \"$t\"")->fetchColumn();
        }
        $results[$t] = ['exists' => (bool) $exists, 'rows' => $count];
    }
} catch (PDOException $e) {
    file_put_contents($reportDir . '/laptop-check-err.txt', $e->getMessage());
    exit(1);
}

$utc = gmdate('Y-m-d\TH:i:s\Z');
$existingTables = array_filter($tables, fn($t) => $results[$t]['exists']);
$missingTables = array_filter($tables, fn($t) => !$results[$t]['exists']);

$dumpCreated = false;
if (!file_exists($exportSql) && !empty($existingTables)) {
    $tFlags = implode(' ', array_map(fn($t) => "-t $t", $existingTables));
    putenv("PGPASSWORD=$pass");
    $cmd = "pg_dump -h " . escapeshellarg($host) . " -U " . escapeshellarg($user) . " -d " . escapeshellarg($db) . " --no-owner --no-privileges $tFlags 2>/dev/null";
    $out = shell_exec($cmd);
    if ($out !== null && strlen($out) > 0) {
        file_put_contents($exportSql, $out);
        $dumpCreated = true;
    }
}

$md = "# Laptop Data Check Report\n\n";
$md .= "## DB Connection\n";
$md .= "- **Source:** config.php (no .env found)\n";
$md .= "- **Host:** $host\n";
$md .= "- **Database:** $db\n";
$md .= "- **User:** $user\n\n";
$md .= "## Table Existence & Row Counts\n";
$md .= "| Table | Exists | Rows |\n|-------|--------|------|\n";
foreach ($tables as $t) {
    $ex = $results[$t]['exists'] ? '1' : '0';
    $md .= "| $t | $ex | {$results[$t]['rows']} |\n";
}
$md .= "\n## Missing Tables\n";
foreach ($missingTables as $t) {
    $md .= "- **$t** (missing)\n";
}
$md .= "\n## Schema & Seed Scripts\n";
$md .= "| Script | Exists | Covers |\n|--------|--------|--------|\n";
$md .= "| database/schema-postgresql.sql | " . (file_exists(__DIR__.'/database/schema-postgresql.sql') ? 'yes' : 'no') . " | stores, daily_kpis |\n";
$md .= "| database/inventory-schema-postgresql.sql | " . (file_exists(__DIR__.'/database/inventory-schema-postgresql.sql') ? 'yes' : 'no') . " | vendors, products, inventory, orders |\n";
$md .= "| database/migrate-timeclock.sql | " . (file_exists(__DIR__.'/database/migrate-timeclock.sql') ? 'yes' : 'no') . " | employees, employee_locations, time_shifts, time_punch_events |\n";
$md .= "| seed-inventory.php | " . (file_exists(__DIR__.'/seed-inventory.php') ? 'yes' : 'no') . " | vendors, products, inventory (sample data) |\n";
$md .= "| seed-timeclock.php | " . (file_exists(__DIR__.'/seed-timeclock.php') ? 'yes' : 'no') . " | employees, employee_locations, time_shifts (sample data) |\n";
$md .= "\n## Export\n";
$md .= "- **File:** artifacts/legacy-export/legacy-pos-tables.sql\n";
$md .= "- **Export UTC:** $utc\n";
$md .= "- **Created:** " . ($dumpCreated ? 'yes' : (file_exists($exportSql) ? 'already existed' : 'no (no tables)')) . "\n";
file_put_contents($reportDir . '/laptop-data-check.md', $md);

$readme = "# Legacy POS Tables Export\n\n";
$readme .= "- **Database:** $db\n";
$readme .= "- **Export UTC:** $utc\n";
$readme .= "- **Row counts:**\n\n";
$readme .= "| Table | Rows |\n|-------|------|\n";
foreach ($existingTables as $t) {
    $readme .= "| $t | {$results[$t]['rows']} |\n";
}
$readme .= "\nGenerated by run-laptop-check.php\n";
file_put_contents($exportDir . '/README.md', $readme);
