#!/bin/bash
# Laptop data check - run in WSL: bash run-laptop-check.sh
set -e
cd "$(dirname "$0")"
export PGPASSWORD="${DB_PASS:-artisan_pass_123}"
DB="${DB_NAME:-artisan_den}"
USER="${DB_USER:-artisan_user}"
HOST="${DB_HOST:-localhost}"

TABLES="stores daily_kpis vendors products inventory orders employees employee_locations time_shifts time_punch_events"
REPORT="docs/reports/laptop-data-check.md"
EXPORT_DIR="artifacts/legacy-export"
EXPORT_SQL="$EXPORT_DIR/legacy-pos-tables.sql"

mkdir -p docs/reports "$EXPORT_DIR"

# 1. Collect table existence and row counts
declare -A ROWS
declare -A EXISTS
for t in $TABLES; do
  ex=$(psql -h "$HOST" -U "$USER" -d "$DB" -t -A -c "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='$t')::int" 2>/dev/null || echo "0")
  EXISTS[$t]=$ex
  if [ "${EXISTS[$t]}" = "1" ]; then
    ROWS[$t]=$(psql -h "$HOST" -U "$USER" -d "$DB" -t -A -c "SELECT COUNT(*) FROM \"$t\"" 2>/dev/null || echo "0")
  else
    ROWS[$t]=0
  fi
done

# 2. Build list of existing tables for pg_dump
EXISTING_TABLES=""
for t in $TABLES; do
  [ "${EXISTS[$t]}" = "1" ] && EXISTING_TABLES="$EXISTING_TABLES -t $t"
done

# 3. Create legacy-pos-tables.sql only if missing
DUMP_CREATED=""
if [ ! -f "$EXPORT_SQL" ] && [ -n "$EXISTING_TABLES" ]; then
  echo "Creating $EXPORT_SQL via pg_dump..."
  pg_dump -h "$HOST" -U "$USER" -d "$DB" --no-owner --no-privileges $EXISTING_TABLES > "$EXPORT_SQL"
  DUMP_CREATED=1
  echo "Created $EXPORT_SQL"
fi

# 4. Generate report
UTC_TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
cat > "$REPORT" << 'REPORT_HEADER'
# Laptop Data Check Report

## DB Connection
- **Source:** config.php (no .env found)
- **Host:** localhost
- **Database:** artisan_den
- **User:** artisan_user

## Table Existence & Row Counts
| Table | Exists | Rows |
|-------|--------|------|
REPORT_HEADER

for t in $TABLES; do
  echo "| $t | ${EXISTS[$t]} | ${ROWS[$t]} |" >> "$REPORT"
done

cat >> "$REPORT" << REPORT_FOOTER

## Missing Tables
REPORT_FOOTER

for t in $TABLES; do
  [ "${EXISTS[$t]}" = "0" ] && echo "- **$t** (missing)" >> "$REPORT"
done

cat >> "$REPORT" << 'REPORT_SCHEMA'

## Schema & Seed Scripts
| Script | Exists | Covers |
|--------|--------|--------|
| database/schema-postgresql.sql | yes | stores, daily_kpis |
| database/inventory-schema-postgresql.sql | yes | vendors, products, inventory, orders |
| database/migrate-timeclock.sql | yes | employees, employee_locations, time_shifts, time_punch_events |
| seed-inventory.php | yes | vendors, products, inventory (sample data) |
| seed-timeclock.php | yes | employees, employee_locations, time_shifts (sample data) |

## Export
- **File:** artifacts/legacy-export/legacy-pos-tables.sql
REPORT_SCHEMA
if [ -n "$DUMP_CREATED" ]; then
  EXPORT_STATUS="created by this run"
elif [ -f "$EXPORT_SQL" ]; then
  [ -s "$EXPORT_SQL" ] && EXPORT_STATUS="already existed" || EXPORT_STATUS="empty (pg_dump may have failed)"
else
  EXPORT_STATUS="not created (no tables or pg_dump failed)"
fi
echo "- **Export UTC:** $UTC_TS" >> "$REPORT"
echo "- **Created:** $EXPORT_STATUS" >> "$REPORT"
echo "" >> "$REPORT"
echo "Run: \`bash run-laptop-check.sh\` in WSL to refresh." >> "$REPORT"

# 5. Update README in legacy-export
{
  echo "# Legacy POS Tables Export"
  echo ""
  echo "- **Database:** $DB"
  echo "- **Export UTC:** $UTC_TS"
  echo "- **Row counts:**"
  echo ""
  echo "| Table | Rows |"
  echo "|-------|------|"
  for t in $TABLES; do
    [ "${EXISTS[$t]}" = "1" ] && echo "| $t | ${ROWS[$t]} |"
  done
  echo ""
  echo "Generated by run-laptop-check.sh"
} > "$EXPORT_DIR/README.md"

echo "Done. Report: $REPORT"
echo "Export: $EXPORT_SQL"
